import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./fontawesome";

const roboto = Roboto({ subsets: ["vietnamese"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "GreenJoy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
